name: mConnect Shared Utility Functions for deno, nodejs and typescript applications

on: [ push, pull_request ]

jobs:
  test:
    runs-on: macos-latest

    strategy:
      matrix:
        deno: [ 1.27.2, 1.28.0, 1.28.1 ]
    name: Test with Deno ${{ matrix.deno }}

    steps:
      - uses: actions/checkout@master

      - name: Setup Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno }}

      - name: Print deno version
        run: deno --version

      - name: Format code using Deno format
        run: deno fmt **/*.ts

      - name: Check format
        run: deno fmt --check **/*.ts

      - name: Build Deno Module
        run: deno run --reload mod.ts

      - name: Run tests - getLocale
        run: deno run test/getLocale.test.ts
      - name: Run tests - collection
        run: deno run test/collection.test.ts
      - name: Run tests - collection2
        run: deno run test/collection2.test.ts
      - name: Run tests - stats
        run: deno run test/stats.test.ts
      - name: Run tests - maths
        run: deno run test/maths.test.ts
      - name: Run tests - validate
        run: deno run test/validate.test.ts
      - name: Run tests - utilFuncs
        run: deno run test/utilFuncs.test.ts
      - name: Run tests - utils (pending - optional)
        run: deno run test/utils.test.ts